[workspace]
members = ["sysfs_api", "sysfs_lib", "sysfs_macros"]

[package]
name = "sysfs"
version = "0.1.0"
edition = "2021"

[dependencies]
sysfs_api = { path = "./sysfs_api" }
sysfs_lib = { path = "./sysfs_lib" }
